require('dotenv').config();
const express = require('express');
const cors = require('cors');
const jwt = require('jsonwebtoken');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const QRCode = require('qrcode');
const { query, transaction, ensureSchema } = require('./db');

const app = express();
const PORT = Number(process.env.PORT || 4000);
const SECRET = process.env.JWT_SECRET || process.env.SECRET_KEY;
if (!SECRET && process.env.NODE_ENV === 'production') throw new Error('JWT_SECRET must be configured in production');
app.use(cors({ origin: process.env.FRONTEND_URL || true, credentials: true }));
app.use(express.json({ limit: '4mb' }));
const sha256 = value => crypto.createHash('sha256').update(String(value)).digest('hex');
const sign = user => jwt.sign({ id: user.id, role: user.role, email: user.email }, SECRET || 'development-only-secret', { expiresIn: '8h' });
function auth(req,res,next){try{const h=req.headers.authorization||'';req.user=jwt.verify(h.startsWith('Bearer ')?h.slice(7):'',SECRET||'development-only-secret');next()}catch{res.status(401).json({error:'Authentication required'})}}
function roles(...allowed){return(req,res,next)=>allowed.includes(req.user.role)?next():res.status(403).json({error:'Insufficient role'})}
function distanceMeters(lat1,lon1,lat2,lon2){const R=6371000,r=d=>d*Math.PI/180,dLat=r(lat2-lat1),dLon=r(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(r(lat1))*Math.cos(r(lat2))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
app.get('/api/health',async(_req,res)=>{try{await query('SELECT 1');res.json({ok:true,service:'KARE ONE API',database:'connected'})}catch{res.status(503).json({ok:false,service:'KARE ONE API',database:'unavailable'})}});
app.post('/api/auth/login',async(req,res)=>{try{const{email,password}=req.body||{};if(!email||!password)return res.status(400).json({error:'Email and password are required'});const q=await query('SELECT * FROM app_users WHERE lower(email)=lower($1)',[email]);const u=q.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Invalid credentials'});res.json({token:sign(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,registerNumber:u.register_number,department:u.department}})}catch(e){console.error(e);res.status(500).json({error:'Login failed'})}});
app.get('/api/me',auth,async(req,res)=>{const q=await query('SELECT id,register_number,name,email,role,department,latitude,longitude FROM app_users WHERE id=$1',[req.user.id]);res.json(q.rows[0]||{})});
app.post('/api/attendance/sessions',auth,roles('faculty','admin'),async(req,res)=>{try{const{subjectId,className,latitude,longitude,allowedRadius=50,durationMinutes=5}=req.body||{};if(!subjectId||!Number.isFinite(latitude)||!Number.isFinite(longitude))return res.status(400).json({error:'Subject and faculty GPS are required'});const radius=Math.min(1000,Math.max(5,Number(allowedRadius)));const duration=Math.min(30,Math.max(1,Number(durationMinutes)));const rawToken=crypto.randomBytes(32).toString('hex');const expiresAt=new Date(Date.now()+duration*60000);const q=await query(`INSERT INTO attendance_sessions(subject_id,faculty_id,class_name,qr_token_hash,faculty_latitude,faculty_longitude,allowed_radius_m,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,expires_at,allowed_radius_m`,[subjectId,req.user.id,className||null,sha256(rawToken),latitude,longitude,radius,expiresAt]);const session=q.rows[0];const qr=await QRCode.toDataURL(JSON.stringify({sessionId:session.id,token:rawToken,expiresAt:session.expires_at}));await query('INSERT INTO audit_logs(user_id,action,details) VALUES($1,$2,$3)',[req.user.id,'ATTENDANCE_SESSION_CREATED',JSON.stringify({sessionId:session.id,subjectId})]);res.status(201).json({session,qr})}catch(e){console.error(e);res.status(500).json({error:'Could not create attendance session'})}});
app.post('/api/attendance/mark',auth,roles('student'),async(req,res)=>{try{const{sessionId,token,latitude,longitude,faceVerified=false,livenessVerified=false}=req.body||{};if(!sessionId||!token||!Number.isFinite(latitude)||!Number.isFinite(longitude))return res.status(400).json({error:'Session, QR and GPS are required'});const q=await query('SELECT * FROM attendance_sessions WHERE id=$1',[sessionId]);const s=q.rows[0];if(!s)return res.status(404).json({error:'Session not found'});if(!s.active||new Date(s.expires_at)<=new Date())return res.status(400).json({error:'QR/session expired'});if(sha256(token)!==s.qr_token_hash)return res.status(400).json({error:'Invalid QR'});if(!faceVerified||!livenessVerified)return res.status(403).json({error:'Face and liveness verification required'});const u=await query("SELECT register_number FROM app_users WHERE id=$1 AND role='student'",[req.user.id]);if(!u.rows[0])return res.status(403).json({error:'Student account required'});const d=distanceMeters(s.faculty_latitude,s.faculty_longitude,latitude,longitude);if(d>Number(s.allowed_radius_m))return res.status(403).json({error:'Outside allowed attendance radius',distanceMeters:d,allowedRadiusMeters:s.allowed_radius_m});const attendance=await transaction(async client=>{const ins=await client.query(`INSERT INTO attendance_records(session_id,student_id,register_number,qr_verified,face_verified,liveness_verified,student_latitude,student_longitude,distance_m,status) VALUES($1,$2,$3,true,$4,$5,$6,$7,$8,'Present') RETURNING *`,[sessionId,req.user.id,u.rows[0].register_number,faceVerified,livenessVerified,latitude,longitude,d]);await client.query('INSERT INTO audit_logs(user_id,action,details) VALUES($1,$2,$3)',[req.user.id,'ATTENDANCE_MARKED',JSON.stringify({sessionId,distanceMeters:d})]);return ins.rows[0]});res.status(201).json({success:true,attendance,distanceMeters:d})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Attendance already registered for this session'});console.error(e);res.status(500).json({error:'Attendance processing failed'})}});
app.get('/api/attendance/my',auth,roles('student'),async(req,res)=>{const q=await query(`SELECT a.*,s.subject_id,s.created_at AS session_created_at FROM attendance_records a JOIN attendance_sessions s ON s.id=a.session_id WHERE a.student_id=$1 ORDER BY a.created_at DESC`,[req.user.id]);res.json(q.rows)});
app.get('/api/attendance/session/:id',auth,roles('faculty','admin'),async(req,res)=>{const q=await query(`SELECT a.*,u.name,u.register_number FROM attendance_records a JOIN app_users u ON u.id=a.student_id WHERE a.session_id=$1 ORDER BY a.created_at`,[req.params.id]);res.json(q.rows)});
async function seedDemoAccounts(){const accounts=[['student@kare.local','Demo Student','student','99240040001','Student@123'],['faculty@kare.local','Demo Faculty','faculty',null,'Faculty@123'],['admin@kare.local','System Admin','admin',null,'Admin@123']];for(const[email,name,role,registerNumber,password]of accounts){const e=await query('SELECT 1 FROM app_users WHERE lower(email)=lower($1)',[email]);if(!e.rowCount){const passwordHash=await bcrypt.hash(password,12);await query('INSERT INTO app_users(email,name,role,register_number,password_hash) VALUES($1,$2,$3,$4,$5)',[email,name,role,registerNumber,passwordHash])}}}
async function start(){await ensureSchema();await seedDemoAccounts();app.listen(PORT,'0.0.0.0',()=>console.log(`KARE ONE API running on ${PORT}`))}
start().catch(e=>{console.error('Startup failed:',e);process.exit(1)});
