require('dotenv').config();
const express=require('express');
const cors=require('cors');
const jwt=require('jsonwebtoken');
const crypto=require('crypto');
const bcrypt=require('bcryptjs');
const QRCode=require('qrcode');
const {Pool}=require('pg');
const app=express();
app.use(cors({origin:process.env.FRONTEND_URL||true}));
app.use(express.json({limit:'4mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const SECRET=process.env.JWT_SECRET||process.env.SECRET_KEY||'change-me';
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
function sign(u){return jwt.sign({id:u.id,role:u.role,email:u.email},SECRET,{expiresIn:'8h'});}
function auth(req,res,next){try{const h=req.headers.authorization||'';req.user=jwt.verify(h.startsWith('Bearer ')?h.slice(7):'',SECRET);next()}catch(e){res.status(401).json({error:'Authentication required'})}}
function roles(...r){return (req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:'Insufficient role'});}
function distance(a,b,c,d){const R=6371000,p=x=>x*Math.PI/180,dp=p(c-a),dl=p(d-b);const x=Math.sin(dp/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'KARE ONE API'}));
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body||{};const q=await pool.query('SELECT * FROM app_users WHERE lower(email)=lower($1)',[email]);const u=q.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Invalid credentials'});res.json({token:sign(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,registerNumber:u.register_number,department:u.department}})}catch(e){console.error(e);res.status(500).json({error:'Login failed'})}});
app.get('/api/me',auth,async(req,res)=>{const q=await pool.query('SELECT id,register_number,name,email,role,department,latitude,longitude FROM app_users WHERE id=$1',[req.user.id]);res.json(q.rows[0]||{})});
app.post('/api/attendance/sessions',auth,roles('faculty','admin'),async(req,res)=>{try{const {subjectId,latitude,longitude,allowedRadius=50,durationMinutes=5}=req.body;if(!subjectId||!Number.isFinite(latitude)||!Number.isFinite(longitude))return res.status(400).json({error:'Subject and faculty GPS are required'});const raw=crypto.randomBytes(32).toString('hex');const exp=new Date(Date.now()+Math.min(30,Math.max(1,durationMinutes))*60000);const q=await pool.query(`INSERT INTO attendance_sessions(subject_id,faculty_id,qr_token_hash,faculty_latitude,faculty_longitude,allowed_radius_m,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,expires_at`,[subjectId,req.user.id,hash(raw),latitude,longitude,allowedRadius,exp]);const qr=await QRCode.toDataURL(JSON.stringify({sessionId:q.rows[0].id,token:raw,expiresAt:exp.toISOString()}));res.json({session:q.rows[0],qr})}catch(e){console.error(e);res.status(500).json({error:'Could not create attendance session'})}});
app.post('/api/attendance/mark',auth,roles('student'),async(req,res)=>{try{const {sessionId,token,latitude,longitude,faceVerified=false,livenessVerified=false}=req.body;if(!sessionId||!token||!Number.isFinite(latitude)||!Number.isFinite(longitude))return res.status(400).json({error:'Session, QR and GPS are required'});const q=await pool.query('SELECT * FROM attendance_sessions WHERE id=$1',[sessionId]);const s=q.rows[0];if(!s)return res.status(404).json({error:'Session not found'});if(!s.active||new Date(s.expires_at)<=new Date())return res.status(400).json({error:'QR/session expired'});if(hash(token)!==s.qr_token_hash)return res.status(400).json({error:'Invalid QR'});const d=distance(s.faculty_latitude,s.faculty_longitude,latitude,longitude);if(d>s.allowed_radius_m)return res.status(403).json({error:'Outside allowed attendance radius',distanceMeters:d});if(!faceVerified||!livenessVerified)return res.status(403).json({error:'Face and liveness verification required'});const u=await pool.query('SELECT register_number FROM app_users WHERE id=$1 AND role=\'student\'',[req.user.id]);if(!u.rows[0])return res.status(403).json({error:'Student account required'});try{const ins=await pool.query(`INSERT INTO attendance_records(session_id,student_id,register_number,qr_verified,face_verified,liveness_verified,student_latitude,student_longitude,distance_m,status) VALUES($1,$2,$3,true,$4,$5,$6,$7,$8,'Present') RETURNING *`,[sessionId,req.user.id,u.rows[0].register_number,faceVerified,livenessVerified,latitude,longitude,d]);await pool.query('INSERT INTO audit_logs(user_id,action,details) VALUES($1,$2,$3)',[req.user.id,'ATTENDANCE_MARKED',JSON.stringify({sessionId,distance:d})]);res.json({success:true,attendance:ins.rows[0],distanceMeters:d})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Attendance already registered for this session'});throw e}}catch(e){console.error(e);res.status(500).json({error:'Attendance processing failed'})}});
app.get('/api/attendance/my',auth,roles('student'),async(req,res)=>{const q=await pool.query(`SELECT a.*,s.id session_id,s.subject_id,s.created_at session_created_at FROM attendance_records a JOIN attendance_sessions s ON s.id=a.session_id WHERE a.student_id=$1 ORDER BY a.created_at DESC`,[req.user.id]);res.json(q.rows)});
app.get('/api/attendance/session/:id',auth,roles('faculty','admin'),async(req,res)=>{const q=await pool.query(`SELECT a.*,u.name,u.register_number FROM attendance_records a JOIN app_users u ON u.id=a.student_id WHERE a.session_id=$1 ORDER BY a.created_at`,[req.params.id]);res.json(q.rows)});
app.listen(process.env.PORT||4000,()=>console.log('KARE ONE API running'));
