/* KARE ONE SIS permission workflow. Injected without changing the existing SIS layout. */
const KARE_PERMISSION_API=(import.meta.env?.VITE_API_URL||'http://localhost:4000/api')+'/permissions';
const permissionToken=()=>localStorage.getItem('kare_token');
const permissionUser=()=>{try{return JSON.parse(localStorage.getItem('kare_user')||'null')}catch{return null}};
async function permissionApi(path='',options={}){const token=permissionToken();const r=await fetch(KARE_PERMISSION_API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Permission request failed');return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusClass(s){return String(s||'Pending').toLowerCase()}
function install(){if(document.getElementById('kare-permission-root'))return;const u=permissionUser();if(!u||!['student','faculty','admin'].includes(u.role))return;
const root=document.createElement('div');root.id='kare-permission-root';root.innerHTML=`<button id="kare-permission-open" class="kp-fab">▣ <span>Permissions</span></button><div class="kp-overlay" hidden><section class="kp-modal"><div class="kp-head"><div><b>Permission Management</b><small>KARE SIS approval workflow</small></div><button id="kp-close">×</button></div><div id="kp-body"></div></section></div>`;document.body.appendChild(root);
const overlay=root.querySelector('.kp-overlay'),body=root.querySelector('#kp-body');root.querySelector('#kare-permission-open').onclick=()=>{overlay.hidden=false;render()};root.querySelector('#kp-close').onclick=()=>overlay.hidden=true;
async function render(){body.innerHTML='<div class="kp-loading">Loading permission requests…</div>';try{if(u.role==='student')return renderStudent();if(u.role==='faculty')return renderReviewer('faculty');return renderReviewer('admin')}catch(e){body.innerHTML=`<div class="kp-error">${esc(e.message)}</div>`}}
async function renderStudent(){const rows=await permissionApi('/mine');body.innerHTML=`<div class="kp-card"><h3>Submit Permission</h3><form id="kp-student-form"><div class="kp-grid"><label>Permission Type<select name="permissionType"><option>Class Permission</option><option>On Duty</option><option>Medical Leave</option><option>Late Entry</option><option>Early Exit</option><option>Other</option></select></label><label>Date<input type="date" name="permissionDate" required></label><label>Start Time<input type="time" name="startTime"></label><label>End Time<input type="time" name="endTime"></label></div><label>Reason<textarea name="reason" required minlength="3" placeholder="Enter the reason for permission…"></textarea></label><button class="kp-primary">Submit Permission</button><span id="kp-msg"></span></form></div><div class="kp-card"><h3>My Requests</h3>${rows.length?`<div class="kp-table">${rows.map(r=>`<div class="kp-row"><div><b>${esc(r.permission_type)}</b><small>${esc(r.permission_date)} ${r.start_time?esc(r.start_time):''}${r.end_time?' – '+esc(r.end_time):''}</small><p>${esc(r.reason)}</p></div><span class="kp-status ${statusClass(r.status)}">${esc(r.status)}</span>${r.status==='Pending'?`<button class="kp-small" data-cancel="${esc(r.id)}">Cancel</button>`:''}</div>`).join('')}</div>`:'<p class="kp-muted">No permission requests yet.</p>'}</div>`;
body.querySelector('#kp-student-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=body.querySelector('#kp-msg');msg.textContent='Submitting…';try{await permissionApi('',{method:'POST',body:JSON.stringify(Object.fromEntries(f.entries()))});msg.textContent='Permission submitted for approval.';e.currentTarget.reset();render()}catch(x){msg.textContent=x.message}};
body.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{try{await permissionApi('/'+b.dataset.cancel+'/cancel',{method:'PATCH'});render()}catch(x){alert(x.message)}})}
async function renderReviewer(role){const rows=await permissionApi(role==='admin'?'/admin/all':'/faculty/pending');body.innerHTML=`<div class="kp-card"><div class="kp-review-head"><h3>${role==='admin'?'All Permission Requests':'Pending Permission Approvals'}</h3><button class="kp-small" id="kp-refresh">Refresh</button></div>${rows.length?`<div class="kp-table">${rows.map(r=>`<div class="kp-row"><div><b>${esc(r.student_name||'Student')} ${r.register_number?'('+esc(r.register_number)+')':''}</b><small>${esc(r.permission_type)} • ${esc(r.permission_date)}${r.subject_code?' • '+esc(r.subject_code):''}</small><p>${esc(r.reason)}</p></div><span class="kp-status ${statusClass(r.status)}">${esc(r.status)}</span>${(r.status==='Pending'||(role==='admin'&&r.status==='Approved'))?`<div class="kp-actions"><button class="kp-approve" data-id="${esc(r.id)}" data-decision="Approved">Approve</button><button class="kp-reject" data-id="${esc(r.id)}" data-decision="Rejected">Reject</button></div>`:''}</div>`).join('')}</div>`:'<p class="kp-muted">No permission requests found.</p>'}</div>`;body.querySelector('#kp-refresh')?.addEventListener('click',render);body.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{const remarks=prompt(`Remarks for ${b.dataset.decision}:`)||'';try{await permissionApi('/'+b.dataset.id+(role==='admin'?'/admin-review':'/review'),{method:'PATCH',body:JSON.stringify({decision:b.dataset.decision,remarks})});render()}catch(x){alert(x.message)}})}
render();}
const boot=()=>{if(permissionUser())install();};window.addEventListener('storage',boot);setTimeout(boot,700);setInterval(()=>{if(permissionUser()&&!document.getElementById('kare-permission-root'))install()},1500);
