import React,{useMemo,useState}from'react';
import{Search,Download,Plus,ExternalLink,IndianRupee,CalendarDays,FileText,CheckCircle2,AlertTriangle,BookOpen,Clock3}from'lucide-react';

const attendance=[
 ['215EXS2201','Design-Build',20,14,0,0,0,70.0],
 ['213CSE3305','Descriptive Analytics',36,26,0,0,0,72.0],
 ['212CSE3303','Operating Systems',35,25,0,0,0,71.0],
 ['212CSE3302','Computer Networks',37,27,0,0,0,73.0],
 ['212CSE3301','Design and Analysis of Algorithms',38,28,0,0,0,74.0]
];
const marks=[
 ['215EXS2201','Design-Build','—','—'],['213CSE3305','Descriptive Analytics','—','—'],['212CSE3303','Operating Systems','—','—'],['212CSE3302','Computer Networks','—','—'],['212CSE3301','Design and Analysis of Algorithms','—','—']
];
const registration=[
 ['212CSE3301','Design and Analysis of Algorithms',4,'Program Core Courses','Integrated Course Theory','Mrs. R. SYED ALI FATHIMA','Regular','Approved'],
 ['212CSE3302','Computer Networks',4,'Program Core Courses','Integrated Course Theory','Mr. B. SHANMUGA RAJA','Regular','Approved'],
 ['212CSE3303','Operating Systems',4,'Program Core Courses','Integrated Course Theory','Dr. A. PARIVAZHAGAN','Regular','Approved'],
 ['213CSE3305','Descriptive Analytics',4,'Program Elective Courses','Integrated Course Theory','Dr. J. BHARATH SINGH','Regular','Approved'],
 ['215EXS2201','Design-Build',3,'Experiential Core','Design Project','DR.M.MURALI','Regular','Approved']
];
const grades=[
 ['1','211CHY1301','Chemistry','3.0','8','C','FC','Nov/Dec 2024'],['1','211EEE1301','Basic Electrical and Electronics Engineering','4.0','8','D','FC','Nov/Dec 2024'],['1','211MAT1301','Linear Algebra and Calculus','4.0','8','C','FC','Nov/Dec 2024'],['2','211BIT1101','Biology for Engineers','3.0','8','C','FC','Apr/May 2025'],['2','211CSE1301','Problem Solving using Computer Programming','3.0','H','E','FC','Apr/May 2025'],['2','211CSE1302','Python Programming','3.0','8','D','FC','Apr/May 2025'],['3','212CSE2301','Data Structures','4.0','8','E','PC','Nov/Dec 2025'],['3','212CSE2302','Digital Principles and System Design','4.0','8','C','PC','Nov/Dec 2025'],['3','212CSE2403','Java Programming','4.0','9','C','PC','Nov/Dec 2025'],['4','212CSE2101','Discrete Mathematics','4.0','8','E','PC','Apr/May 2026'],['4','212CSE2303','Software Engineering','3.0','8','C','PC','Apr/May 2026'],['4','212CSE2304','Machine Learning','4.0','8','E','PC','Apr/May 2026'],['4','212CSE2305','Database Management Systems','4.0','8','D','PC','Apr/May 2026'],['4','213CSE2301','Predictive Analytics','4.0','8','E','PE','Apr/May 2026'],['4','PHT511','Value Addition in Fruits and Vegetables','3.0','8','B','UE','Apr/May 2026']
];
const noncgpa=[['1','21ECS1102','Soft Skills II','0.5','1','Apr/May 2026']];
const mandatory=[['1','MAN18R001','Environmental Science','Nov/Dec 2025'],['2','MAN18R002','Indian Constitution','Nov/Dec 2025']];
const timetable=[
 ['Monday','212CSE3301','09:00 AM - 09:50 AM','Room / Faculty TBA'],['Monday','213CSE3305','11:00 AM - 11:50 AM','Room / Faculty TBA'],['Monday','213CSE3305','12:00 PM - 12:50 PM','Room / Faculty TBA'],['Monday','215EXS2201','02:00 PM - 02:50 PM','Room / Faculty TBA'],['Monday','212CSE3302','03:00 PM - 03:50 PM','Room / Faculty TBA'],['Tuesday','212CSE3302','09:00 AM - 09:50 AM','Room / Faculty TBA'],['Tuesday','212CSE3303','11:00 AM - 11:50 AM','Room / Faculty TBA'],['Tuesday','212CSE3303','12:00 PM - 12:50 PM','Room / Faculty TBA'],['Wednesday','213CSE3305','10:00 AM - 10:50 AM','Room / Faculty TBA'],['Wednesday','212CSE3301','11:00 AM - 11:50 AM','Room / Faculty TBA'],['Thursday','212CSE3302','09:00 AM - 09:50 AM','Room / Faculty TBA'],['Thursday','212CSE3303','10:00 AM - 10:50 AM','Room / Faculty TBA'],['Friday','212CSE3301','09:00 AM - 09:50 AM','Room / Faculty TBA'],['Friday','212CSE3303','03:00 PM - 03:50 PM','Room / Faculty TBA'],['Friday','213CSE3305','04:00 PM - 04:50 PM','Room / Faculty TBA']
];
const category=[['Experiential Core (EC)',16,'—','—',16],['Experiential Elective (EE)',8,'—','—',8],['Foundation Core (FC)',44,42,39,5],['Honours (HO)',20,'—','—',20],['Minors (MI)',20,'—','—',20],['Program Core (PC)',52,30,30,22],['Program Elective Courses (PE)',24,7,7,17],['University Elective Courses (UE)',16,6,6,10],['Total',180,85,82,98]];
const facultyRows=[['CS101','Computer Science & Engineering','Current semester','Active'],['CS102','Data Analytics','Current semester','Active'],['CS103','Operating Systems','Current semester','Active']];
const studentRows=[['99240040001','Demo Student','Computer Science and Engineering','2024','24S19','Active'],['99240040002','Demo Student 2','Computer Science and Engineering','2024','24S19','Active'],['99240040003','Demo Student 3','Information Technology','2024','24S20','Active']];

function Table({columns,rows,searchable=true,actions}){const[q,setQ]=useState(''),[page,setPage]=useState(1),size=8;const filtered=useMemo(()=>rows.filter(r=>r.some(v=>String(v??'').toLowerCase().includes(q.toLowerCase()))),[rows,q]);const pages=Math.max(1,Math.ceil(filtered.length/size));const shown=filtered.slice((page-1)*size,page*size);return <><div className="sis-tools"><span>Show {Math.min(size,filtered.length)} of {filtered.length} entries</span>{searchable&&<label className="sis-search"><Search/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search..."/></label>}</div><div className="sis-table-wrap"><table className="sis-table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}{actions&&<th>Action</th>}</tr></thead><tbody>{shown.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{typeof v==='string'&&/^(Approved|Active|Present|Published|Clear)$/.test(v)?<span className="badge ok">{v}</span>:v}</td>)}{actions&&<td><button className="sis-action" onClick={()=>actions(r)}>Open</button></td>}</tr>)}</tbody></table></div><div className="sis-pagination"><span>Showing {filtered.length?((page-1)*size+1):0} to {Math.min(page*size,filtered.length)} of {filtered.length}</span><div><button disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button>{Array.from({length:pages},(_,i)=><button key={i} className={page===i+1?'current':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={page===pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button></div></div></>}
function Frame({title,subtitle,children,actions}){return <div className="sis-module"><div className="sis-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><div className="sis-title-actions">{actions}</div></div>{children}</div>}
function SummaryCards({items}){return <div className="sis-summary">{items.map(([a,b,c])=><div key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>}

export default function SISModule({page,role,setPage}){
 if(page==='Attendance Details')return <Frame title="Attendance Details" subtitle="Semester attendance record"><Table columns={['Code','Course Name','Conducted','Attended','Leave','Medical','OD','Attendance %']} rows={attendance.map(r=>[...r.slice(0,7),<span className={r[7]<80?'badge warn':'badge ok'}>{r[7]}%</span>])}/><div className="sis-note"><AlertTriangle/> Attendance below 80% is highlighted. Secure attendance is available through QR + GPS + server validation.</div></Frame>;
 if(page==='Mark Details')return <Frame title="Marks Details KARE" subtitle="Continuous assessment and semester marks"><Table columns={['Course Code','Course Name','Internal','End Semester','Status']} rows={marks.map(r=>[...r.slice(0,2),r[2],r[3],'Published'])}/></Frame>;
 if(page==='Registration'||page==='Course Registration')return <Frame title="Registration Details" subtitle="Academic Semester 2026-27"><Table columns={['Course Code','Course Name','Credits','Category','Theory / Practical','Faculty','Type','Status']} rows={registration}/><div className="sis-note"><CheckCircle2/> Current registrations are shown with approval state. New registration requests require the configured academic workflow.</div></Frame>;
 if(page==='Grade')return <Frame title="Grade Details KARE" subtitle="Consolidated semester grade history"><SummaryCards items={[['CGPA','6.12','Current cumulative record'],['Earned Credits','82.0','Credits earned'],['Arrears','1','Current arrear count']]}/><Table columns={['Sem','Course Code','Course Name','Credits','Att.Code','Grade','Category','Year of Passing']} rows={grades}/><h3 className="sis-section-heading">Credit Requirement Summary</h3><Table columns={['Category','Minimum Credits','Studied','Earned','To Be Earned']} rows={category}/></Frame>;
 if(page==='Non-CGPA'||page==='CPG')return <Frame title="NonCGPA Details KARE" subtitle="Non-CGPA, mandatory and audit activities"><Table columns={['S.No','Course Code','Course Name','Credits','Group / Mark','Year of Passing']} rows={noncgpa}/><h3 className="sis-section-heading">Mandatory Courses</h3><Table columns={['S.No','Course Code','Course Name','Year of Passing']} rows={mandatory}/><h3 className="sis-section-heading">Audit Courses</h3><Table columns={['S.No','Course Code','Course Name','Year of Passing']} rows={[]}/></Frame>;
 if(page==='Seating & Time Table'||page==='Timetable')return <Frame title="Seating & Time Table" subtitle="Weekly class timetable and examination seating"><Table columns={['Day','Course Code','Time','Room / Faculty']} rows={timetable}/><div className="sis-note"><CalendarDays/> Examination seating is populated after the examination administrator publishes room and seat allocation.</div></Frame>;
 if(page==='Fees'||page==='Fees & Payments')return <Frame title={role==='admin'?'Fees & Payments':'Fees'} subtitle="Fee ledger and payment status"><SummaryCards items={[['Current Due','₹0','No pending balance in demo account'],['Paid This Term','₹0','Transactions recorded'],['Payment Gateway','Not configured','No fake payment success']]} /><Table columns={['Fee Type','Amount','Due Date','Status','Receipt']} rows={[['Tuition Fee','₹0','—','Clear','—'],['Examination Fee','₹0','—','Clear','—'],['Hostel / Transport','₹0','—','Clear','—']]}/><button className="primary" onClick={()=>alert('Payment gateway not configured') }><IndianRupee/> Pay Fees</button></Frame>;
 if(page==='Results')return <Frame title="Results" subtitle="Published semester results"><SummaryCards items={[['CGPA','6.12','Cumulative'],['Earned Credits','82','Current record'],['Status','Published','Latest available result']]}/><Table columns={['Semester','SGPA','CGPA','Earned Credits','Published']} rows={[['Semester 1','6.80','6.80','21','Published'],['Semester 2','6.10','6.42','20','Published'],['Semester 3','5.98','6.12','21','Published'],['Semester 4','6.15','6.12','20','Published']]}/></Frame>;
 if(page==='Online Courses'||page==='One Credit'||page==='Online/Intern/IT Courses')return <Frame title={page} subtitle="Course permission and completion records"><Table columns={['Course / Activity','Type','Credits','Status','Action']} rows={[['Online course permission','Online Course','—','Pending Approval','Request'],['One Credit Course','One Credit','1','Not Registered','Register'],['Internship / IT Course','Intern / IT','—','Pending Approval','Request']]}/><button className="outline" onClick={()=>setPage('Permissions')}><Plus/> Request Permission</button></Frame>;
 if(page==='Course Feedback')return <Frame title="Course Feedback" subtitle="Submit feedback for registered courses"><Table columns={['Course Code','Course Name','Faculty','Feedback Status','Action']} rows={registration.map(r=>[r[0],r[1],r[5],'Pending','Give Feedback'])}/></Frame>;
 if(page==='Circulars')return <Frame title="Circulars" subtitle="University announcements and notices"><Table columns={['Date','Title','Category','Status']} rows={[['2026-08-30','Academic Activities Circular','Academic','Published'],['2026-08-28','Examination Schedule Notice','Examination','Published'],['2026-08-20','Course Registration Notice','Registration','Published']]}/></Frame>;
 if(page==='Hostel Booking'||page==='Transport Booking')return <Frame title={page} subtitle="Connected institutional booking service"><div className="sis-empty"><BuildingIcon/><b>{page} service</b><p>Booking status and requests are shown here when the institutional provider is connected.</p><button className="primary" onClick={()=>alert('External booking provider not configured')}>Open Booking</button></div></Frame>;
 if(page==='Academic Calendar')return <Frame title="Academic Calendar" subtitle="Academic year 2026-27"><Table columns={['Date','Event','Category','Description']} rows={[['2026-09-01','Semester Begins','Academic','Odd Semester 2026-27'],['2026-09-20','Sessional Examination','Examination','Published schedule'],['2026-11-10','End Semester Examination','Examination','Schedule subject to publication']]}/></Frame>;
 if(page==='Students')return <Frame title="Student Management" subtitle="Search and manage student records"><Table columns={['Register No','Name','Programme','Batch','Section','Status']} rows={studentRows}/></Frame>;
 if(page==='Faculty')return <Frame title="Faculty Management" subtitle="Teaching staff directory"><Table columns={['Employee / Code','Faculty Area','Term','Status']} rows={facultyRows}/></Frame>;
 if(page==='Subjects & Classes'||page==='My Courses')return <Frame title={page} subtitle="Subjects, classes and faculty assignments"><Table columns={['Code','Subject','Credits','Category','Faculty','Class','Status']} rows={registration.map(r=>[r[0],r[1],r[2],r[3],r[5],'CSE-A','Active'])}/></Frame>;
 if(page==='Attendance Reports'||page==='Attendance Monitor')return <Frame title={page} subtitle="Attendance monitoring and analytics"><SummaryCards items={[['Active Sessions','0','Live right now'],['Students Present','0','Current session count'],['Low Attendance','2','Requires attention']]}/><Table columns={['Course','Conducted','Attended','Average %','Risk']} rows={attendance.map(r=>[r[0],r[2],r[3],`${r[7]}%`,r[7]<80?'At Risk':'Healthy'])}/></Frame>;
 if(page==='Reports')return <Frame title="Reports" subtitle="Institutional reports and exports"><div className="sis-report-grid">{['Student Report','Attendance Report','Examination Report','Fee Report','Result Report','Permission Report'].map(x=><button key={x} className="report-card" onClick={()=>alert(`${x} export will use the live database when the report endpoint is configured.`)}><FileText/>{x}<Download/></button>)}</div></Frame>;
 if(page==='System Settings')return <Frame title="System Settings" subtitle="Role-based configuration"><Table columns={['Setting','Current State','Action']} rows={[['JWT Authentication','Enabled','Review'],['PostgreSQL','Connected','Health Check'],['Face / Liveness Provider','Not configured','Configure'],['Payment Gateway','Not configured','Configure'],['Attendance Radius','50 m default','Update']]}/></Frame>;
 return <Frame title={page} subtitle="KARE SIS module"><div className="sis-empty"><BookOpen/><b>Module ready</b><p>This page is structured for the same SIS-style tables, search, pagination and role-based actions. Connect its API endpoint when institutional data is available.</p></div></Frame>;
}
function BuildingIcon(){return <ExternalLink/>}
